drop table if exists bookmarks;

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text not null,
  url text not null,
  description text,
  rating INTEGER default 5
);

insert into bookmarks (title, url, description, rating)
values
  ('Thinkful', 'http://www.thinkful.com', 'this is a the thinkful homepage', 5),
  ('Google', 'http://www.google.com', 'this is a the Google homepage', 4),
  ('Gmail', 'http://www.gmail.om', 'this is a the Gmail homepage', 3),
  ('Facebook', 'http://www.Facebook.com', 'this is a the Facebook homepage', 2),
  ('Foo', 'http://www.foo.com', 'this is a the Foo homepage', 1),
  ('Amazon', 'http://www.amazon.com', 'this is a the Amazon homepage', 2),
  ('Bar', 'http://www.bar.com', 'this is a the Bar homepage', 3),
  ('Test', 'http://www.test.com', 'this is a the Test homepage', 4),
  ('Cats', 'http://www.cats.com', 'this is a the Cats homepage', 5),
  ('Music', 'http://www.music.com', 'this is a the Music homepage', 4),
  ('Dogs', 'http://www.dogs.com', 'this is a the Dogs homepage', 3);
